### ISSUE TITLE
bug: saving user data

### ISSUE THREAD

**Issue by akeshavan** [ChildMindInstitute/mindlogger-web#16]
for some reason, saving user data doesn't work anymore (#1) -- it was working earlier today, now I get a 500 response (internal server error). Any ideas @shnizzedy ?

**Comment by shnizzedy** [comment]
The problem was `"applet": undefined` was being passed to `api.sendActivityData` in the `data` Object, and the route required a string in that Object. I updated the route to

1. Prefer Objects to strings in both `data.applet` and `data.activity`, preferring the following keys (in order of preference)
    1. `@id`
    2. `skos:prefLabel`
    3. `name`
2. Accept strings if passed instead of Objects
3. Save in `[Unknown Applet]` if `data.applet` is neither an Object or a string.
